const lerp=(a,b,f)=>a+(b-a)*f;
export function createTelemetrySampler(trackLength){
const distanceBetween=(a,b,f)=>{const span=b[1]-a[1];if(span<=0)return a[1];const dt=b[0]-a[0],maxSlope=3*span,raw0=Math.max(0,a[2])*dt/(3.6*trackLength),raw1=Math.max(0,b[2])*dt/(3.6*trackLength),factor=Math.min(1,maxSlope/Math.max(raw0+raw1,1e-9)),m0=raw0*factor,m1=raw1*factor,t=f*f,t3=t*f;return (2*t3-3*t+1)*a[1]+(t3-2*t+f)*m0+(-2*t3+3*t)*b[1]+(t3-t)*m1};
const sampleState=(driver,t,out={})=>{const samples=driver.samples,last=samples.length-1;if(t<=0){var a=samples[0],b=a,f=0}else if(t>=driver.duration){a=samples[last];b=a;f=0}else{let low=0,high=last;while(high-low>1){const mid=(low+high)>>1;if(samples[mid][0]<=t)low=mid;else high=mid}a=samples[low];b=samples[high];f=(t-a[0])/(b[0]-a[0])}out.u=distanceBetween(a,b,f);out.speed=lerp(a[2],b[2],f);out.throttle=lerp(a[3],b[3],f);out.brake=f<.5?a[4]:b[4];out.gear=Math.round(lerp(a[5],b[5],f));out.rpm=Math.round(lerp(a[6],b[6],f));out.lateral=lerp(a[7],b[7],f);return out};
const timeAtDistance=(driver,u)=>{const samples=driver.samples,last=samples.length-1;if(u<=0)return 0;if(u>=1)return driver.duration;let low=0,high=last;while(high-low>1){const mid=(low+high)>>1;if(samples[mid][1]<=u)low=mid;else high=mid}const a=samples[low],b=samples[high];let left=0,right=1;for(let j=0;j<12;j++){const mid=(left+right)/2;if(distanceBetween(a,b,mid)<u)left=mid;else right=mid}return lerp(a[0],b[0],(left+right)/2)};
const inputAtDistance=(driver,u,out={})=>{const samples=driver.samples,last=samples.length-1;if(u<=0){var a=samples[0],b=a,f=0}else if(u>=1){a=samples[last];b=a;f=0}else{let low=0,high=last;while(high-low>1){const mid=(low+high)>>1;if(samples[mid][1]<=u)low=mid;else high=mid}a=samples[low];b=samples[high];f=(u-a[1])/(b[1]-a[1])}out.throttle=lerp(a[3],b[3],f);out.brake=f<.5?a[4]:b[4];return out};
const lateralAtDistance=(driver,u)=>{const samples=driver.samples,last=samples.length-1;if(u<=0)return samples[0][7];if(u>=1)return samples[last][7];let low=0,high=last;while(high-low>1){const mid=(low+high)>>1;if(samples[mid][1]<=u)low=mid;else high=mid}const a=samples[low],b=samples[high],f=(u-a[1])/(b[1]-a[1]);return lerp(a[7],b[7],f)};

return {sampleState,timeAtDistance,inputAtDistance,lateralAtDistance,distanceBetween};
}
