import * as T from '../../vendor/three.module.js';
import {GLTFLoader} from '../../vendor/GLTFLoader.js';
export async function createCars({scene,renderer,drivers,registry,assetURL,comparisonIndex=1}){
const paintFactories=new Map();
for(const driver of drivers){const definition=registry.cars[driver.carId];if(!definition)throw Error('Unknown car: '+driver.carId);if(!paintFactories.has(definition.livery)){const module=await import(assetURL(definition.livery));paintFactories.set(definition.livery,module.createPaint);}}
function wedge(wf0,wr0,h,length){const wf=wf0/2,wr=wr0/2,l=length/2,v=[-wr,0,-l,wr,0,-l,-wf,0,l,wf,0,l,-wr,h,-l,wr,h,-l,-wf,h*.52,l,wf,h*.52,l],f=[0,2,1,1,2,3,4,5,6,5,7,6,0,1,4,1,5,4,2,6,3,3,6,7,0,4,2,2,4,6,1,3,5,3,7,5],g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(f);g.computeVertexNormals();return g}
function makeCar(accent,comparison=false){const group=new T.Group(),materials=[],ghostMat=(color,roughness,metalness=0)=>{const m=new T.MeshPhysicalMaterial({color,roughness,metalness,clearcoat:.75,clearcoatRoughness:.22,transparent:comparison,opacity:comparison?.76:1});materials.push(m);return m},carbon=ghostMat('#101416',.32,.4),paint=ghostMat('#d8dede',.22,.62),accentMat=ghostMat(accent,.25,.5),tireMat=ghostMat('#07090a',.82),metal=ghostMat('#747d80',.2,.85),mesh=(g,m,x,y,z,rx=0,ry=0,rz=0)=>{const o=new T.Mesh(g,m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);o.castShadow=true;o.receiveShadow=true;group.add(o);return o};mesh(new T.BoxGeometry(1.75,.11,5.2),carbon,0,.28,0);mesh(wedge(.22,1.05,.42,4.25),paint,0,.42,.45);const spine=mesh(new T.CapsuleGeometry(.38,2.4,7,14),paint,0,.68,-.45,Math.PI/2);spine.scale.set(1,1,.9);mesh(wedge(.62,1.3,.72,2.05),accentMat,0,.52,-.65);for(const side of[-1,1]){mesh(wedge(.33,.72,.55,2.15),carbon,side*.73,.44,-.62,0,0,side*.04);mesh(new T.BoxGeometry(.16,.08,3.1),accentMat,side*.56,.78,-.18);mesh(new T.BoxGeometry(.06,.05,2.65),metal,side*.54,.86,-.2)}mesh(new T.BoxGeometry(2.35,.11,.5),carbon,0,.3,2.5);mesh(new T.BoxGeometry(1.76,.08,.34),accentMat,0,.48,2.38);for(const side of[-1,1])mesh(new T.BoxGeometry(.09,.32,.55),carbon,side*1.05,.45,2.47);mesh(new T.BoxGeometry(2.15,.12,.45),accentMat,0,1.04,-2.13);mesh(new T.BoxGeometry(1.9,.09,.28),carbon,0,1.28,-2.16);for(const side of[-1,1])mesh(new T.BoxGeometry(.08,.65,.46),carbon,side*.91,.88,-2.13);const cockpit=mesh(new T.SphereGeometry(.42,18,10),carbon,0,1.02,-.18);cockpit.scale.set(.9,.6,1.25);const helmet=mesh(new T.SphereGeometry(.23,16,10),ghostMat('#e8d36d',.25,.15),0,1.25,.1);helmet.scale.set(1,.92,1);mesh(new T.TorusGeometry(.36,.045,8,20,Math.PI*1.75),carbon,0,1.31,.08,Math.PI/2,0,.2);mesh(new T.CylinderGeometry(.045,.045,.7,8),carbon,0,1.25,.2,0,0,Math.PI/2);for(const side of[-1,1])for(const z of[-1.43,1.55]){mesh(new T.CylinderGeometry(.42,.42,.44,24),tireMat,side*.98,.44,z,0,0,Math.PI/2);mesh(new T.CylinderGeometry(.18,.18,.46,16),metal,side*.98,.44,z,0,0,Math.PI/2);const ring=mesh(new T.TorusGeometry(.29,.025,6,24),accentMat,side*1.205,.44,z,0,Math.PI/2);ring.castShadow=false}mesh(new T.BoxGeometry(.8,.06,1.5),accentMat,0,.79,.25);group.scale.setScalar(2.16);scene.add(group);return{group,materials}}
const templates=new Map();
for(const driver of drivers){const definition=registry.cars[driver.carId];if(!definition)throw Error("Unknown car: "+driver.carId);if(!templates.has(definition.model)){templates.set(definition.model,(await new GLTFLoader().loadAsync(assetURL(definition.model))).scene);}}
function makeDetailedCar(driver,comparison=false){
  const definition=registry.cars[driver.carId],driverNumber=driver.driver_number,carTemplate=templates.get(definition.model);
  if(!carTemplate)return makeCar('#00b9ad',comparison);
  const group=new T.Group(),model=carTemplate.clone(true),alpha=comparison?.76:1;
  const pbr=(color,roughness,metalness)=>new T.MeshPhysicalMaterial({color,roughness,metalness,clearcoat:.9,clearcoatRoughness:.16,transparent:comparison,opacity:alpha,depthWrite:!comparison,side:T.DoubleSide});
  const carbon=pbr('#111619',.29,.56),dark=pbr('#252b2d',.24,.7),metal=pbr('#889194',.2,.9),body=pbr('#ffffff',.32,.48),tire=pbr('#080909',.88,.02),cockpit=pbr('#15191b',.2,.62),materials=[carbon,body,cockpit,metal,dark,tire];
  const paint=paintFactories.get(definition.livery)(driverNumber,Math.min(4,renderer.capabilities.getMaxAnisotropy()));paint(body);paint(dark);
  body.roughness=dark.roughness=definition.roughness??.32;
  const materialBySourceName={'Default_OBJ.003':carbon,'Default_OBJ.004':body,'Default_OBJ.002':cockpit,'Default_OBJ.001':carbon,'Default_OBJ.009':metal,'Default_OBJ.008':body,'Default_OBJ.007':dark,'Default_OBJ.006':tire,'Default_OBJ.005':body};
  const remapMaterial=source=>materialBySourceName[source?.name]||body;
  model.traverse(node=>{if(!node.isMesh)return;node.material=Array.isArray(node.material)?node.material.map(remapMaterial):remapMaterial(node.material);node.castShadow=true;node.receiveShadow=true;node.frustumCulled=false});
  model.scale.setScalar(definition.scale);model.rotation.y=definition.rotationY;const box=new T.Box3().setFromObject(model),carCenter=box.getCenter(new T.Vector3());model.position.x-=carCenter.x;model.position.z-=carCenter.z;model.position.y-=box.min.y;group.add(model);scene.add(group);return{group,materials};
}

return drivers.map((driver,index)=>makeDetailedCar(driver,index===comparisonIndex));
}
